apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekEwTVRNeApOakU0TWpGYUZ3MDBNekEwTVRNeE5qRTRNakZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEakpuSHUrZjRRd2Y2SlE0dElGN3FCK1ZHNGVBZkM2czBjNjlIcEhPL0luaDB1dWl6MgpuSWpueStpUXRIUkNQanFEZ0xVREdUZU5zY0tPQTErQlFPNHIyQ09Jais1L1QyMmVRMmVHRXdjZmU0STh1dkhLCnlQbXBaNm9JaHJPNHNNOXpkWnJWb2hPZFNhL1FUTGNWT2UxMFJDUjd6OC92V01HZkN5eDRRclRXNlpHTFBJRGMKZFdXdCs1cHRzUjBFa055RktzRi9pK1ppSUljUmJHYjNDZFJIWlFiMGtla2gwcVJDa3NkWnpOSXlwMFErSnUrQwo0VGxFOGZTTG5kd2tQbXpBWm4yZ29vR1hwS3R1ZGV4bERkYVNGcGM4Qk5pTHhmOGtmQUNienZCT3dVWWVsUGpCCnBlSGxTYU54bUpMOFpGLzE5YWxQTVVKejczUjJacmc2d3dXN0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFxcmYxaUxtRVZ6SjMvNXIvTgprUEsvMHNPQmxEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFVeHlqNUVubzU2L1VkMU83YVp0UUhaYzlySWU0ClBzUGNVYWl5aVJUMUVnSWw1SmZEbHk4bUg5YVRvSVhCSHZiQW8zU3l6ZjJYd25oMmFlai85SE14dDhEL1ErUG8KdWVLRkExdGxiYXc2SEpaSXFqWFc2WWQ1Qlo5aStQa29jdW9vTlBBZytQODZRZEMyY3BWRjNNajU0WVBmY1BpMQo2aFE4WTlzbThDalcybnJOWDdacmxBaXppN0tYSUx0NnFTL1ZvdWxWR1ZPMkJHc3JvMTAxTmY2SGFrVEpBd1cvCnVaS2o1ZzBLM2xaUWZBQkFrSzduRFJmaEUwRUVybW9ZZmd3anZTMFJQZVJkUlkrNEdjcEFNdzBOS0NLQ3FaVW0KbjEwUzdBR2Njb1hqSVZaaGdsekYwK014eStEVGJiK3RYT2IrTkJmQ3NBb0RVUTZpL1pEZW0rL0RGZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3c675d41-a70b-434c-87c1-2f57c389156f.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_0d3f041618a4d34b170b8a24eb789a2d7b3d088e8e0293a8980eb37f9780dc73
